apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant1-deployment
spec:
  replicas: 1 #Number of desired replicas
  selector:
    matchLabels:
      app: nextjs-portfolio-tenant1
  template:
    metadata:
      labels:
        app: nextjs-portfolio-tenant1
    spec:
      containers:
      - name: nextjs-portfolio-tenant1
        image: sourav2805/nextjs-portfolio:tenant1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
