apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant2-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant2-portfolio
  template:
    metadata:
      labels:
        app: tenant2-portfolio
    spec:
      containers:
        - name: tenant2-portfolio
          image: "docker-tenant-2:latest"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tenant2-portfolio-service
spec:
  selector:
    app: tenant2-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant2-portfolio-ingress
spec:
  rules:
    - host: "tenant2.charlie.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tenant2-portfolio-service
                port:
                  number: 80
