apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant2-deployment
spec:
  replicas: 1 #Number of desired replicas
  selector:
    matchLabels:
      app: nextjs-portfolio-tenant2
  template:
    metadata:
      labels:
        app: nextjs-portfolio-tenant2
    spec:
      containers:
      - name: nextjs-portfolio-tenant2
        image: sourav2805/nextjs-portfolio:tenant2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "4000" # Set the app to listen on port 4000
        ports:
        - containerPort: 4000
